import type { Metadata } from 'next';

import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ClientProvider } from '../app-providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <body className={cn('text-base antialiased', inter.className)}>
                <ClientProvider>{children}</ClientProvider>
            </body>
        </html>
    );
}
