name: Semantic Release

on:
    #    push:
    #        branches:
    #            - main
    #            - dev/*
    #            - feature/*
    #            - hotfix/*
    workflow_dispatch:

jobs:
    ci:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '24'
            - run: npm ci
            - run: npm run lint

    semantic-release:
        needs: ['ci']

        if: "!contains(github.event.head_commit.message, '[skip ci]')"

        name: Semantic Release
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false
            # - name: Semantic Release
            #   uses: ./.github/workflows/semantic-release
            #   with:
            #       branch: ${{ github.ref_name }}
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Do something after release
              run: |
                  echo 42
