name: On Release Published

on:
    release:
        types: [published]

jobs:
    after-release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - name: Print info
              run: |
                  echo "Release published!"
                  echo "Tag: ${{ github.event.release.tag_name }}"
                  echo "Name: ${{ github.event.release.name }}"
